server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: catalog-service
    
  mongodb:
    embedded:
      version: 4.0.2
    data:
      mongodb:
        database: catalog
        port: 27018

  rabbitmq:
    username: guest
    password: guest
    localhost: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

queue:
  serie:
    name: SerieQueue
  movie:
    name: MovieQueue
  
   
message: Queues Up

//circuit breaker
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: circuitbreakers,circuitbreakerevents,health,info,ratelimiters,metrics
    health:
        circuitbreakers:
            enabled: true
resilience4j:
    circuitbreaker:
        instances:
            subscription:
                serie:
                    allowHealthIndicatorToFail: false
                    automaticTransitionFromOpenToHalfOpenEnabled: true
                    failureRateThreshold: 50
                    permittedNumberOfCallsInHalfOpenState: 3
                    registerHealthIndicator: true
                    slidingWindowSize: 5
                    slidingWindowType: COUNT_BASED
                    waitDurationInOpenState: 15000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
