server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: catalogRoute
          uri: http://localhost:8082  
          predicates:
            - Path=/catalog/**  

        - id: movieRoute
          uri: http://localhost:8083  
          predicates:
            - Path=/movie/** 