server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: catalogRoute
          uri: http://localhost:8082  
          predicates:
            - Path=/catalog/**  

        - id: movieRoute
          uri: http://localhost:8083  
          predicates:
            - Path=/movie/** 
