server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      default-filters:
        - name: LogFilter
      routes:
        - id: catalogRoute
          uri: http://localhost:61886
          predicates:
            - Path=/catalog/**  

        - id: movieRoute
          uri:  http://localhost:61927
          predicates:
            - Path=/movie/** 
          filters:
          - AddRequestHeader:user-request-header,custom-user-request-header
          - AddResponseHeader:user-response-header,custom-user-response-header
